### ISSUE TITLE
Do we have a python version? thank you!

### ISSUE THREAD

**Issue by johnson7788** [teapot123/JASen#2]
Do we have a python version?

**Comment by teapot123** [comment]
Hi Johnson, Thanks for asking! For the embedding training part, we only have the c implementation by modifying the original Word2Vec code. This is because c version is rather efficient in embedding training on large corpus than a python version. However, after we obtain the word and topic embeddings, we use convolutional neural nets to further finetune the results. The neural net part is implemented in python version (in evaluation.py) and takes the trained embedding as input. I am not sure are you interested in the python version of the embedding part or the neural net part?
